name: Run Tests

on: [push, pull_request] # runs this file for every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # tells file to look at entire repository
      uses: actions/checkout@v2

    - name: Set up Python # insstalls python version 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies # installs everything else we need to run the file
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install scipy

    - name: Run tests  # tests our "test_co2_functions.py" file
      run: pytest test_co2_functions.py
